output_dir: ./results
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5e-5
weight_decay: 0.01
logging_steps: 100
evaluation_strategy: steps
eval_steps: 500
save_steps: 1000
save_total_limit: 3
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
warmup_steps: 0
fp16: false
dataloader_num_workers: 2
remove_unused_columns: true