# Prometheus configuration for Code Explainer monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'code-explainer'
    environment: 'production'

# Scrape configurations
scrape_configs:
  # Code Explainer API metrics
  - job_name: 'code-explainer-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
