name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of what the bug is.
      placeholder: Short summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/traceback
      description: Paste any relevant logs.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `python -c "import code_explainer as c; print(c.__version__)"`
  - type: dropdown
    id: env
    attributes:
      label: Environment
      options:
        - macOS
        - Linux
        - Windows
