name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion!
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the feature.
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your proposed solution.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
