"""Initial database schema

Revision ID: fefce1f791bf
Revises: 
Create Date: 2026-03-16 13:18:46.634073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefce1f791bf'
down_revision: str = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_operation', 'audit_logs', ['operation'], unique=False)
    op.create_index('idx_audit_request', 'audit_logs', ['request_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('cache_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_accessed', 'cache_entries', ['last_accessed'], unique=False)
    op.create_index('idx_cache_created', 'cache_entries', ['created_at'], unique=False)
    op.create_index('idx_cache_type', 'cache_entries', ['cache_type'], unique=False)
    op.create_index(op.f('ix_cache_entries_cache_key'), 'cache_entries', ['cache_key'], unique=True)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=False),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_model', 'model_metrics', ['model_name'], unique=False)
    op.create_index('idx_metrics_operation', 'model_metrics', ['operation'], unique=False)
    op.create_index('idx_metrics_timestamp', 'model_metrics', ['timestamp'], unique=False)
    op.create_table('request_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('request_size_bytes', sa.Integer(), nullable=True),
    sa.Column('response_size_bytes', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_endpoint', 'request_history', ['endpoint'], unique=False)
    op.create_index('idx_request_status', 'request_history', ['status_code'], unique=False)
    op.create_index('idx_request_timestamp', 'request_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_history_request_id'), 'request_history', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_history_request_id'), table_name='request_history')
    op.drop_index('idx_request_timestamp', table_name='request_history')
    op.drop_index('idx_request_status', table_name='request_history')
    op.drop_index('idx_request_endpoint', table_name='request_history')
    op.drop_table('request_history')
    op.drop_index('idx_metrics_timestamp', table_name='model_metrics')
    op.drop_index('idx_metrics_operation', table_name='model_metrics')
    op.drop_index('idx_metrics_model', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_cache_entries_cache_key'), table_name='cache_entries')
    op.drop_index('idx_cache_type', table_name='cache_entries')
    op.drop_index('idx_cache_created', table_name='cache_entries')
    op.drop_index('idx_cache_accessed', table_name='cache_entries')
    op.drop_table('cache_entries')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_request', table_name='audit_logs')
    op.drop_index('idx_audit_operation', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###