name: Docs & Eval Nightly

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -e .
          pip install mkdocs mkdocs-material mkdocstrings-python
      - name: Build docs
        run: mkdocs build --strict
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

  eval-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -e .[dev]
      - name: Run smoke eval
        run: |
          code-explainer eval --dataset humaneval --max-samples 5 --report out/smoke.md || true