name: Nightly Eval

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run eval (fast)
        run: |
          code-explainer eval --config configs/default.yaml --test-file data/test.json || true
